apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tasks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sesaquecruz/tasks-app-backend:1.1.0
        resources:
          limits:
            memory: "700Mi"
            cpu: "350m"
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: backend-cfgmap
