apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tasks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sesaquecruz/java-tasks-api:1.2.0
        resources:
          limits:
            memory: "700Mi"
            cpu: "350m"
        startupProbe:
          httpGet:
            path: /api/v1/actuator/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /api/v1/actuator/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /api/v1/actuator/health
            port: 8080
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
          successThreshold: 1
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: backend-secret
        - configMapRef:
            name: backend-cfgmap
