apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: tasks-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: backend
    kind: Deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80