apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: tasks-app
type: Opaque
data:
  MYSQL_URL: bXlzcWwtMC5teXNxbC1zZXJ2aWNlOjMzMDYvdGFza3M=
  MYSQL_USERNAME: dGFza3MtYXBw
  MYSQL_PASSWORD: dGFza3MtYXBwMTIz