apiVersion: v1
kind: Pod
metadata:
  name: mysql-flyway
  namespace: tasks-app
spec:
  containers:
  - name: mysql-flyway
    image: sesaquecruz/mysql-tasks-database:1.0.0-flyway
    resources:
      limits:
        cpu: "0.15"
        memory: 150Mi
    envFrom:
    - secretRef:
        name: mysql-flyway-secret
    command: ["flyway", "migrate"]
  restartPolicy: Never