apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mail@sesaque.com
    privateKeySecretRef:
      name: letsencrypt-issuer-secret
    solvers:
      - http01:
          ingress:
            class: nginx