apiVersion: v1
kind: Pod
metadata:
  name: flyway
  namespace: tasks-app
spec:
  containers:
  - name: flyway
    image: sesaquecruz/tasks-app-database:1.0.0
    resources:
      limits:
        cpu: "0.15"
        memory: 150Mi
    envFrom:
    - secretRef:
        name: mysql-flyway-secret
    command: ["flyway", "migrate"]
  restartPolicy: Never