apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  mysql-volume-claim
  namespace: tasks-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo