apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: tasks-app
spec:
  serviceName: mysql-service
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccount: tasks-app-account
      containers:
      - name: mysql
        image: mysql:8.0.32
        resources:
          requests: 
            cpu: "0.5"
            memory: 500Mi
          limits:
            cpu: "1"
            memory: 1Gi
        startupProbe:
          exec:
            command: ["mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD", "ping"]
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          exec:
            command: ["mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD", "ping"]
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          exec:
            command: ["mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD", "ping"]
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
          successThreshold: 1
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql-secret
        volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-volume-claim